name: Workflow1 Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    uses: actions/checkout@v2
    name: hello world
    run: echo "hello world"
    shell: bash

  job2:
    runs-on: ubuntu-latest
    steps:
    name: goodbye
    run: echo "goodbye aja"
    shell: bash
