name: Workflow1 ok
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  jobs1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello world
        run: echo Hello, world!
        shell: bash
  jobs2:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye
        run: echo "Goodbye"
        shell: bash
  jobs3:
    runs-on: ubuntu-latest
    steps:
      - name: selamat datang
        run: echo "selamat datang"
        shell: bash
